# 服务端口
server:
  port: 8004
# 服务名
spring:
  application:
    name: service-cms
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: root
  # redis数据库连接
  redis:
    host: 192.168.206.128
    port: 6379
    database: 0
    timeout: 180000
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 20
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1
        # 连接池中的最大空闲连接 默认为8
        max-idle: 5
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  #配置mapper xml文件的路径
  mapper-locations: classpath:com/sorlin/cms/mapper/xml/*.xml
  configuration:
    #mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl