# 服务端口
server:
  port: 8005
# 服务名
spring:
  application:
    name: service-msm
  # redis数据库连接
  redis:
    host: 192.168.206.128
    port: 6379
    database: 0
    timeout: 180000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  #配置mapper xml文件的路径
  mapper-locations: classpath:com/sorlin/cms/mapper/xml/*.xml
  configuration:
    #mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  msm:
    file:
      keyid: "你的keyid"
      keysecret: "你的keysecret"